use crate::util;
use anyhow::{Context, Result};
use pyro_core::ast::Stmt;
use pyro_core::transpiler::Transpiler;
use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

pub fn r#impl(file: PathBuf, output: Option<PathBuf>) -> Result<()> {
    println!("Building {:?}", file);

    let mut statements = Vec::new();
    let mut loaded = HashSet::new();
    
    util::process_file(file.clone(), &mut loaded, &mut statements)?;

    // Split statements into definitions (top-level) and executable statements (main)
    let mut defs = Vec::new();
    let mut main_stmts = Vec::new();

    for stmt in statements {
        match stmt {
            Stmt::FnDecl { .. } => defs.push(stmt),
            _ => main_stmts.push(stmt),
        }
    }

    let mut transpiler = Transpiler::new();
    
    let defs_rs = transpiler.transpile(defs);
    let main_rs = transpiler.transpile(main_stmts);

    let full_rs = format!(r#"
// Generated by Pyro
fn main() {{
{}
}}

// Definitions
{}
"#, main_rs, defs_rs);

    // Setup build directory
    let build_dir = PathBuf::from("target/pyro_build");
    if build_dir.exists() {
        fs::remove_dir_all(&build_dir)?;
    }
    fs::create_dir_all(build_dir.join("src"))?;

    // Write Main.rs
    fs::write(build_dir.join("src/main.rs"), full_rs)?;

    // Write Cargo.toml
    let cargo_toml = r#"[package]
name = "pyro_program"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
"#;
    fs::write(build_dir.join("Cargo.toml"), cargo_toml)?;

    println!("Compiling to native binary...");
    
    let status = Command::new("cargo")
        .arg("build")
        .arg("--release")
        .current_dir(&build_dir)
        .status()
        .context("Failed to run cargo build")?;

    if !status.success() {
        anyhow::bail!("Compilation failed");
    }

    // Copy binary
    let dest = if let Some(out) = output {
        out
    } else {
        let bin_name = file.file_stem().unwrap().to_str().unwrap();
        PathBuf::from(bin_name)
    };
    
    fs::copy(build_dir.join("target/release/pyro_program"), &dest)?;

    println!("Build successful! Binary created: {:?}", dest);

    Ok(())
}
